updates - sorry for not posting these to github for a long time

diff --git a/grabber b/grabber
--- a/grabber
+++ b/grabber
@@ -5,14 +5,14 @@
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/gpl-2.0.html>,
 # or in pdf format at <http://www.dhampir.no/stuff/private/gpl-2.0.pdf>
 
-# Copyright 2014 - Øyvind 'bolt' Hvidsten   <bolt@dhampir.no>
+# Copyright 2014 - Øyvind 'bolt' Hvidsten	<bolt@dhampir.no>
 
 # Description:
 #
@@ -38,6 +38,8 @@
 # 2015-08-22: Added support for $grab_method
 # 2015-08-26: Added support for $grab_auth
 # 2016-01-16: Renamed "encode" function to match shellfunc naming
+# 2016-06-22: Added "silent" and "show-error" to avoid having progress output in the stderr file
+# 2017-11-19: Added support for fetching headers only, and for avoiding redirection
 #
 
 
@@ -72,46 +74,78 @@ function grab
 {
 	>"$f_stdout"
 	>"$f_stderr"
-	local i
 	local agent=${GRABBER_AGENT:-"Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0"}
 	local timeout=${GRABBER_TIMEOUT:-30}
 	local retries=${GRABBER_RETRIES:-3}
+	local compressed; if ${GRABBER_COMPRESSED:-true}; then compressed="x"; else compressed=""; fi
+
+	local header_only=""
+	local no_redirect=""
+	local redirect="x"
+	local fail=true
+	OPTIND=1
+	while getopts ":hrn" opt; do
+		case "$opt" in
+			h) header_only="x" ;;
+			r) no_redirect="x"; redirect="" ;;
+			n) fail=false ;;
+			[?])
+				echo "Unknown option -${OPTARG}" >&2
+				exit 1
+			;;
+			:)
+				echo "Option -${OPTARG} requires an argument" >&2
+				exit 1
+			;;
+		esac
+	done
+	shift $((OPTIND-1))
+	if [[ "${1:-}" = "--" ]]; then shift; fi
+
 	{
 		case "${GRABBER:-curl}" in
 			curl)
 				_grabber_grab curl \
-					--location \
+					${redirect:+--location --max-redirs 25} \
 					--insecure \
-					--cookie $f_cookies \
-					--cookie-jar $f_cookies \
+					--cookie "$f_cookies" \
+					--cookie-jar "$f_cookies" \
 					--speed-limit 1 \
-					--speed-time $timeout \
-					--connect-timeout $timeout \
-					--retry $retries \
+					--speed-time "$timeout" \
+					--connect-timeout "$timeout" \
+					--retry "$retries" \
 					--user-agent "$agent" \
+					--silent --show-error \
 					${grab_proto:+-"$grab_proto"} \
 					${grab_data:+--data "$grab_data"} \
 					${grab_ref:+--referer "$grab_ref"} \
 					${grab_head:+--header "$grab_head"} \
 					${grab_method:+--request "$grab_method"} \
 					${grab_auth:+--user "$grab_auth"} \
+					${compressed:+--compressed} \
+					${no_redirect:+--max-redirs 0} \
+					${header_only:+-I} \
 					"$@" >"$f_stdout" 2>"$f_stderr"
 			;;
 			wget)
 				_grabber_grab wget -O- \
 					--no-check-certificate \
-					--load-cookies=$f_cookies \
-					--save-cookies=$f_cookies \
+					--load-cookies="$f_cookies" \
+					--save-cookies="$f_cookies" \
 					--keep-session-cookies \
-					--timeout $timeout \
-					--tries $retries \
+					--timeout "$timeout" \
+					--tries "$retries" \
 					--user-agent="$agent" \
+					--no-verbose \
 					${grab_proto:+-"$grab_proto"} \
 					${grab_data:+--post-data="$grab_data"} \
 					${grab_ref:+--referer="$grab_ref"} \
 					${grab_head:+--header="$grab_head"} \
 					${grab_method:+--method="$grab_method"} \
 					${grab_auth:+--user="${grab_auth%%:*}" --password="${grab_auth#*:}"} \
+					${no_redirect:+--max-redirect=0} \
+					${redirect:+--max-redirect=25} \
+					${header_only:+-S --spider} \
 					"$@" >"$f_stdout" 2>"$f_stderr"
 			;;
 			*)
@@ -121,7 +155,7 @@ function grab
 		esac
 	} && grab_status=$? || grab_status=$?
 	(( grab_status )) || return 0
-	grabber_fail
+	! $fail || grabber_fail
 }
 
 
@@ -140,7 +174,7 @@ function assert
 		_grabber_silent || echo "OK"
 	else
 		_grabber_silent || echo "Failed!"
-		echo "Exiting due to failed assertion (${@})" >&2
+		echo "Exiting due to failed assertion (${*})" >&2
 		_grabber_debugfail
 		${GRABBER_EXIT:-true} && exit 1 || return 1
 	fi
@@ -150,7 +184,8 @@ function assert
 # Simple URL encoding - just encode everything
 function sf_urlencode
 {
-	local encoded=$(xxd -plain <<<"${@:-$(cat)}" | tr -d '\n' | sed 's/\(..\)/%\1/g')
+	local encoded
+	encoded=$(xxd -plain <<<"${*:-$(cat)}" | tr -d '\n' | sed 's/\(..\)/%\1/g')
 	echo "${encoded%\%0a}"
 }
 
@@ -158,7 +193,7 @@ function sf_urlencode
 # Debug printing
 function grabber_debug
 {
-	! ${DEBUG:-false} || echo "Debug: $@" >&2
+	! ${DEBUG:-false} || echo "Debug: $*" >&2
 }
 
 
@@ -185,7 +220,7 @@ function _grabber_silent
 }
 function grabber_task
 {
-	_grabber_silent || echo -n "$@... "
+	_grabber_silent || printf '%s' "${*}... "
 }
 function grabber_ok
 {
diff --git a/telenorsms b/telenorsms
--- a/telenorsms
+++ b/telenorsms
@@ -72,6 +72,11 @@
 # 2015-05-01: Minimal fix to support new link format for the login page
 # 2015-05-16: Updated to comply with changes to grabber
 # 2016-01-16: Updated to comply with changes to grabber (again)
+# 2016-12-29: Fix "bad substitution" error in Debian Stretch Bash
+# 2017-02-03: Support for accounts with multiple phone numbers
+#             In related news: support for the minemeldinger.no API in development
+# 2017-07-21: Code cleanup, hopefully no functional changes
+# 2017-11-19: Implemented support for Telenor's new oAuth login
 #
 
 
@@ -111,7 +116,8 @@ config="$HOME/.${_scriptname}"
 
 
 # Smart Sourcing
-function ssource {
+function ssource
+{
     while (( $# )); do
         if [[ -f "$1" ]] && [[ -r "$1" ]]; then
             source "$1"
@@ -124,7 +130,7 @@ function ssource {
 
 
 # Grabber
-grabber=$(grep -m 1 "^grabber=" $config 2>/dev/null | cut -d = -f 2)
+grabber=$(grep -m 1 "^grabber=" "$config" 2>/dev/null | cut -d = -f 2)
 if ! ssource /cathedral/src/lib/grabber "${grabber:-"$HOME/.grabber"}" "$(dirname "${BASH_SOURCE[0]}")/grabber"; then
 	echo "grabber library was not found" >&2
 	echo "Please download \"grabber\" from the same place you got this script," >&2
@@ -134,8 +140,9 @@ fi
 
 
 # Config
-username=$(grep -m 1 "^username=" $config 2>/dev/null | cut -d = -f 2 | sf_urlencode)
-password=$(grep -m 1 "^password=" $config 2>/dev/null | cut -d = -f 2 | sf_urlencode)
+username=$(grep -m 1 "^username=" "$config" 2>/dev/null | cut -d = -f 2 | sf_urlencode)
+password=$(grep -m 1 "^password=" "$config" 2>/dev/null | cut -d = -f 2 | sf_urlencode)
+subscription=$(grep -m 1 "^subscription=" "$config" 2>/dev/null | cut -d = -f 2)
 [[ -z "${1:-}" ]] || { recipient=$1 && shift; }
 [[ -z "${1:-}" ]] || { message=$(sf_urlencode "$@"); }
 
@@ -151,19 +158,52 @@ if [[ -z "${recipient:-}" ]] || [[ -z "${message:-}" ]]; then
 fi
 
 
+# Get login URL
+grabber_task "Getting login URL"
+grab -hrn "https://www.telenor.no/privat/minesider/logginn" || :
+cat "$f_stderr" >>"$f_stdout"
+assert 'Location: '
+read -r login_url < <(grep -m 1 "Location: " <"$f_stdout" | cut -d ':' -f 2- | tr -d '\r\n') || :
+
+
 # Get cookie
 grabber_task "Getting cookie"
-grab "https://www.telenor.no/privat/minesider/logginnfelles.cms"
-assert 'action="/privat/minesider/logginnfelles.cms'
+grab "$login_url"
+assert 'action="#"'
 
 
 # Login
 grabber_task "Logging in"
+grab_data="username=$username&password=$password" \
+grab_ref="$login_url" \
+grab "$login_url"
+assert "Authentication successful"
+
+
+# Get form data
+grabber_task "Getting form data"
+function field_value
+{
+	local name=$1
+	local regex="<input[^>]+name=\"$name\"[^>]+value=\"([^\"]+)"
+	if [[ "$(tr -d '\r\n' <"$f_stdout")" =~ $regex ]]; then
+		printf '%s' "${BASH_REMATCH[1]}"
+	else
+		grabber_fail
+	fi
+}
+fdata_1=$(field_value "samlResponse")
+fdata_2=$(field_value "telenor_id")
+fdata_3=$(field_value "last_success_login_date")
+grabber_ok
+
+# Login
+grabber_task "Accessing service"
 up=false
 while true; do
-	grab_data="usr_name=$username&usr_password=$password&lbAction=Logg+inn" \
-	grab_ref="https://www.telenor.no/privat/minesider/logginnfelles.cms" \
-	grab "https://www.telenor.no/privat/minesider/logginnfelles.cms"
+	grab_data="samlResponse=$(sf_urlencode "${fdata_1}")&telenor_id=$(sf_urlencode "${fdata_2}")&last_success_login_date=$(sf_urlencode "${fdata_3}")" \
+	grab_ref="$login_url" \
+	grab "https://apigw.telenor.no/oauth/v2/storeSaml"
 	if found 'SEND_SMS'; then
 		echo "OK"
 		break
@@ -184,14 +224,60 @@ while true; do
 done
 
 
-# Mandatory SMS page get...
-grabber_task "SMS page get"
+# Subscription test
+grabber_task "Looking for subscription"
+smsurl="https://www.telenor.no/privat/minesider/norm/win/sms/send.do"
 grab_ref="https://www.telenor.no/privat/minesider/minside/minSidePage.cms" \
-grab "https://www.telenor.no/privat/minesider/norm/win/sms/send.do"
+grab "$smsurl"
 if found '<h1>Teknisk feil</h1>'; then
 	grabber_fail '"Teknisk feil" - Have you activated SMS from Web yet?'
 fi
-assert 'action="/norm/win/sms/send/process.do"'
+if found '/selectSubscription/process.do'; then
+	>"$f_stderr" # hijack this
+	echo 'It would seem you have more than one subscription' >>"$f_stderr"
+	echo 'Please add one of the following "subscription=..." lines to your configuration file:' >>"$f_stderr"
+	while IFS=$'\t' read -r sub ref; do
+		if [[ "$sub" = "${subscription:-x}" ]]; then
+			smsurl="https://telenormobil.no$ref"
+			break
+		fi
+		echo "subscription=$sub" >>"$f_stderr"
+	done < <(
+		grep '/selectSubscription/process.do' "$f_stdout" | cut -d '"' -f 2,4 --output-delimiter=$'\t' | tr -d ' '
+	)
+
+	# list subscriptions available
+	if [[ -z "$smsurl" ]]; then
+		echo "???" >&2
+		cat "$f_stderr" >&2
+		exit 1
+	fi
+
+	# attempt to select subscription
+	grabber_ok
+	grabber_task "Number verification"
+	select_url=$smsurl
+	for (( i=0; i<10; i++)); do
+		grab -hrn "$select_url" || :
+		cat "$f_stderr" >>"$f_stdout"
+		read -r select_url < <(grep -m 1 "Location: " <"$f_stdout" | cut -d ':' -f 2- | tr -d '\r\n') || :
+		if [[ "$select_url" = *"send.do" ]]; then
+			break
+		fi
+	done
+	if [[ "$select_url" != *"send.do" ]]; then
+		echo "???" >&2
+		echo "Failed to select number for sending - have you send a message manually and verified the code yet?" >&2
+		exit 1
+	fi
+fi
+grabber_ok
+
+
+# Mandatory SMS page get...
+grabber_task "SMS page get"
+grab "$smsurl"
+assert '/send/process.do'
 
 
 # Get the address list
@@ -220,11 +306,11 @@ while read -r line; do
 	fi
 done <"$f_stdout"
 grabber_ok
-echo "Read ${#names[@]:-} entries from address list."
+echo "Read ${#names[@]} entries from address list."
 
 
 # Translate recipients given as names to numbers in the address list
-for (( i=0; i<${#names[@]:-}; i++ )); do
+for (( i=0; i<${#names[@]}; i++ )); do
 	if [[ "${recipient,,}" = "${names[i],,}" ]]; then
 		recipient=${numbers[i]}
 		break
@@ -234,7 +320,7 @@ done
 
 # Translate recipients given as partial numbers (or translated above) to full numbers and announce
 match=false
-for (( i=0; i<${#numbers[@]:-}; i++ )); do
+for (( i=0; i<${#numbers[@]}; i++ )); do
 	if
 		[[ "$recipient" = *"${numbers[i]}"* ]] ||
 		[[ "${numbers[i]}" = *"$recipient"* ]]
